{
 "title": "Internet Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "In and out (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(snmp_ifInOctets_17[5m]) / 1024^2",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(snmp_ifOutOctets_17[5m]) / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "snmp_ifOperStatus_17", "legendFormat": "__auto" },
    { "expr": "snmp_ifAdminStatus_17", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "snmp_sysUpTime_0 / 100", "legendFormat": "__auto" }
   ]
  }
 ]
}