global:
  scrape_interval: 8s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'home-network-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself

  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273'] # Replace with the address of the Telegraf service

  - job_name: 'blackbox'
    metrics_path: '/probe'
    params:
      module: [http_2xx] # Blackbox exporter module, define more if needed
    static_configs:
      - targets:
          - 'http://www.google.com' # Replace with the URLs you want to monitor
          - 'http://www.cloudflare.com'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox_exporter:9115' # Address of the blackbox exporter

# Add additional scrape targets as needed
